# Complete la configuracion local de AIDE para el TP2.
# La base activa debe ser /srv/tp2/aide/aide.db
# La base nueva debe ser /srv/tp2/aide/aide.db.new
# El reporte debe escribirse en stdout con detalle de atributos cambiados.

# database_in
database_in=file:/srv/tp2/aide/aide.db
# database_out
database_out=file:/srv/tp2/aide/aide.db.new
# report_level
report_level=changed_attributes
# report_url
report_url=stdout

# definicion TP2NORMAL  para verificar permisos, tipo, inode, enlaces,
# propietario, grupo, tamanio, tiempos y SHA-256.
TP2NORMAL = p+ftype+i+l+u+g+s+acl+sha256
# aplique TP2NORMAL solamente a /srv/tp2/datos.
/srv/tp2/datos TP2NORMAL
